### ISSUE TITLE
Replace CompilerMetadataResolver

### ISSUE THREAD

**Issue by gastonambrogi** [douglasduteil/angular-batscanner#21]
When you say: 
> You will need to replace the default `CompilerMetadataResolver` with `BatscannerCompilerMetadataResolver` to be able to extract the activity of the all components at runtime.

How I replace it?

**Comment by DrYurii** [comment]
The documentation sucks, this in not the only unclear point

**Comment by gastonambrogi** [comment]
You can propose the change or enhancement making it by your own 😊
